name: 'GuiEngine'
version: '${project.version}'
main: io.github.toberocat.guiengine.GuiEngineApiPlugin
depend:
  - ToberoCore
api-version: 1.16
authors: [ Tobero ]
commands:
  guiengine:
    description: View your guis