name: 'GuiEngine'
version: '1.0.0'
main: io.github.toberocat.guiengine.api.GuiEngineApiPlugin
depend:
  - ToberoCore
api-version: 1.16
authors: [ Tobero ]
commands:
  guiengine:
    description: View your guis